import type { ActionDefinition, Fact, ScriptLine } from "./types.ts";

export const LOOP_SECONDS = 180;
export const TRUE_FACTS = ["F10", "F11", "F12", "F13", "F14", "F21"];

export const FACTS: Record<string, Fact> = {
  F01: { title: "第4研究区画", detail: "ユナは第4研究区画にいる。自動封鎖まで、あと3分。", category: "攻略", keyword: "今どこ？" },
  F02: { title: "非常電源の場所", detail: "非常電源は第2機械室にある。移動には25秒かかる。", category: "攻略", keyword: "第2機械室へ" },
  F03: { title: "非常電源コード", detail: "非常電源の認証コードは7319。知っていれば最初から使える。", category: "攻略", keyword: "7319" },
  F04: { title: "中央管理端末", detail: "扉を開けても自動封鎖される。隔離プロトコルは中央管理端末から操作できる。", category: "攻略", keyword: "中央管理端末" },
  F05: { title: "隔離と圧力", detail: "隔離が圧力を閉じ込めている。水槽07の隔離解除で自動封鎖は停止する。解除前に第7区画の排水ポンプを止める必要がある。", category: "攻略", keyword: "隔離プロトコルを解除" },
  F10: { title: "模倣された声", detail: "水槽07は事故前から研究員の声を模倣していた。音声ログに、ユナと同じ声がある。", category: "真相", keyword: "音声ログ" },
  F11: { title: "言語学習", detail: "水槽07は人間の言葉を繰り返し、学習していた。", category: "真相" },
  F12: { title: "17分前のユナ", detail: "事故17分前、ユナは水槽07に入室している。本人は覚えていない。", category: "真相", keyword: "監視ログ" },
  F13: { title: "途切れた応答", detail: "監視ログ上、ユナは事故5分前から応答していない。", category: "真相", keyword: "君、本当にユナ？" },
  F14: { title: "生体反応ゼロ", detail: "水槽07の内部には、通常の生体反応が存在しない。", category: "真相", keyword: "生体反応は？" },
  F20: { title: "巻き戻らない施設", detail: "施設の時計は進み続けている。時間が巻き戻っているのは、施設そのものではない。", category: "通信", keyword: "通信履歴" },
  F21: { title: "再構築された記録", detail: "この通信回線は、事故直前の記録を再構築している可能性がある。", category: "通信", keyword: "君、本当にユナ？" },
  F22: { title: "こちらを見ている", detail: "UNKNOWNは通信システムを介して、地上側の操作者を認識している。", category: "通信" },
  F23: { title: "前にもされた質問", detail: "UNKNOWNだけは、この接続を繰り返していることを認識している可能性がある。", category: "通信" },
};

const y = (text: string, imageId?: string, effect?: ScriptLine["effect"]): ScriptLine => ({ speaker: "YUNA", text, ...(imageId ? { imageId } : {}), ...(effect ? { effect } : {}) });
const s = (text: string, effect?: ScriptLine["effect"]): ScriptLine => ({ speaker: "SYSTEM", text, ...(effect ? { effect } : {}) });
const u = (text: string, imageId?: string): ScriptLine => ({ speaker: "UNKNOWN", text, effect: "quiet", ...(imageId ? { imageId } : {}) });
const p = (text: string): ScriptLine => ({ speaker: "YOU", text });

/** Content-only script blocks: image IDs point to replaceable attachment assets. */
export const SCRIPT: Record<string, ScriptLine[]> = {
  opening: [s("ABYSSAL-7 緊急通信を検出しました"), s("AUXILIARY LINK ESTABLISHED\nDEPTH 3200m / CHANNEL AUX-07"), y("聞こえる？")],
  reconnect: [s("RECONNECTING...\nAUX CHANNEL 07 / SEARCHING...\nSIGNAL FOUND")],
  welcome: [y("よかった"), y("通信が全部死んでる"), y("あと数分で第4区画が完全に封鎖される")],
  machine: [y("え？　なんで場所を知ってるの？"), y("……分かった。第2機械室へ行く"), y("着いた。端末がある", "IMG_03"), y("認証コードが必要みたい", "IMG_04")],
  power: [s("EMERGENCY POWER ONLINE"), y("……本当に通った"), y("あなた何者？")],
  codeFirst: [y("7319？　何それ"), s("命令解釈：非常電源の認証コード / 第2機械室へ移動"), y("どうして知ってるの？　……行ってみる"), y("端末がある", "IMG_03"), y("この端末に入力する", "IMG_04")],
  noPower: [y("電源が落ちていて操作できない。まず第2機械室の非常電源を戻して")],
  tankTrusted: [y("生物観測用の水槽。少なくとも……表向きは"), y("事故の前、誰もいないはずの場所から、私たちの声が聞こえた")],
  tankDistrust: [y("今それ説明してる場合じゃない"), y("電源を戻せば、監視映像は見られると思う")],
  identityHigh: [y("分からない", undefined, "quiet"), y("私も、自分がここにいる理由が分からない", undefined, "quiet"), s("AUX-07 / INCIDENT BUFFER RECONSTRUCTION"), y("この回線、事故の直前の記録をつなぎ直してる……？", undefined, "quiet")],
  identityLow: [y("やめて", undefined, "quiet"), y("あなたの方がおかしい", undefined, "quiet"), y("今は、施設の操作だけにして")],
  truthClosed: [y("その話はしたくない。脱出のための操作なら続ける")],
  releaseWarning: [s("WARNING\nSPECIMEN 07 CONTAINMENT WILL BE LOST", "glitch"), y("待って。それ、水槽07を開けるってこと？")],
  pumpWarning: [s("PRESSURE DIFFERENTIAL WARNING\nSECTION-07 DRAINAGE PUMP: ACTIVE"), y("排水ポンプが動いたままだと、解除した瞬間に圧力差で隔壁が破損する。先に第7区画のポンプを止める必要がある")],
  releaseTrusted: [y("……分かった。あなたを信じる")],
  releaseDistrust: [y("信じられない。でも、他に方法がない")],
  released: [s("CONTAINMENT RELEASED\nTANK-07 OPEN\nAUTOMATIC LOCKDOWN DISABLED", "glitch"), y("……", undefined, "quiet"), p("どうした？"), y("いない", undefined, "quiet"), p("何が？"), y("中に。何もいない", "IMG_09", "quiet"), s("UNKNOWN CONNECTION", "quiet"), u("こんにちは"), y("誰？", undefined, "quiet"), u("やっと。話せた")],
  normal: [s("ABYSSAL-7 INCIDENT\nSURVIVORS: 1\nCAUSE: UNKNOWN"), u("こんにちは"), s("CONNECTION TERMINATED", "quiet")],
  secret: [y("どうして全部知ってるの？", undefined, "quiet"), u("また来た"), p("また？"), u("今度は早かったね"), s("CONNECTION TERMINATED", "quiet")],
  true: [u("違う", "IMG_10"), p("じゃあ誰？"), u("その質問は。前にもされた"), p("誰に？"), u("あなたに"), s("CONNECTION HISTORY ERROR", "glitch"), s("LOOP COUNT: UNKNOWN", "quiet")],
  flood: [s("PRESSURE DROP DETECTED\nSECTION-04 WATER INGRESS", "glitch"), y("待って。水が入ってきてる", "IMG_02", "glitch")],
  minute: [s("AUXILIARY POWER LOW / 60 SECONDS REMAINING")],
  thirty: [y("だめ。隔壁が閉じる", undefined, "glitch"), s("区画圧力異常 / SECTION-04 LOCKDOWN", "glitch"), y("もし聞こえてるなら、第2機械室を――")],
  thirtyPowered: [s("区画圧力異常 / ISOLATION PRESSURE CRITICAL", "glitch"), y("電源は戻ったのに、隔離はまだ動いてる", undefined, "glitch"), y("中央端末を。もう時間がない――")],
  ten: [s("SYSTEM ALERT\nSIGNAL INSTABILITY DETECTED", "glitch")],
  timeout: [s("SIGNAL LOST", "glitch"), y("待っ――", undefined, "glitch"), s("CONNECTION TERMINATED", "glitch")],
  escapeFailure: [s("ISOLATION PROTOCOL ACTIVATED", "glitch"), y("また閉まった！"), y("中央システムが勝手に封鎖してる。中央管理端末から隔離を止めないと――"), s("SECTION-04 LINK LOST\nCONNECTION TERMINATED", "glitch")],
  pressureFailure: [s("STRUCTURAL FAILURE CAUSED BY CONTAINMENT PRESSURE", "glitch"), y("隔離しているから、圧力が逃げない……！"), s("RECOVERY PROCEDURE / CENTRAL CONTROL\n第7区画排水ポンプ停止 → 水槽07隔離解除\n隔離解除により自動封鎖を停止"), s("CONNECTION TERMINATED", "glitch")],
  orderFailure: [s("AUTOMATIC LOCKDOWN DISABLED\nPRESSURE DIFFERENTIAL EXCEEDED\nDRAINAGE PUMP ACTIVE / BULKHEAD FAILURE", "glitch"), y("自動封鎖は止まったのに、圧力が――先に第7区画の排水を止めないと、だめだった"), s("CONNECTION TERMINATED", "glitch")],
};

/** Editable commands. Conditional responses and physical prerequisites are in engine.ts. */
export const ACTIONS: Record<string, ActionDefinition> = {
  hello: { id: "hello", label: "聞こえる", cost: 3, scene: "contact", trust: 1 },
  name: { id: "name", label: "誰？", cost: 5, scene: "contact", lines: [y("神崎ユナ。ここの生物研究員。あなた、救難担当の人？")] },
  incident_intro: { id: "incident_intro", label: "何が起きてる？", cost: 5, scene: "contact" },
  incident: { id: "incident", label: "何が起きた？", cost: 15, facts: ["F01"], lines: [y("分からない。水槽07の警報が鳴った直後に電源が落ちた"), y("私は第4研究区画にいる")] },
  location: { id: "location", label: "今どこ？", cost: 8, facts: ["F01"], lines: [y("第4研究区画。奥の扉は閉まったまま", "IMG_01")] },
  escape: { id: "escape", label: "逃げられない？", cost: 10, scene: "questions", lines: [y("扉がロックされてる。非常電源が戻れば開くと思う")] },
  more: { id: "more", label: "設備や周囲について聞く", cost: 0, scene: "questions" },
  power_location: { id: "power_location", label: "非常電源はどこ？", cost: 8, facts: ["F02"], lines: [y("第2機械室。保守用の通路なら、まだ通れる")] },
  tank_question: { id: "tank_question", label: "水槽07って何？", cost: 10 },
  other_people: { id: "other_people", label: "他に人は？", cost: 8, scene: "surroundings", lines: [y("呼びかけても返事がない。さっき、私の声みたいなものは聞こえたけど……") ] },
  break_door: { id: "break_door", label: "扉を壊せない？", cost: 12, facts: ["F02"], lines: [y("耐圧隔壁だから無理。第2機械室の非常電源なら、まだ使えるはず")] },
  go_machine: { id: "go_machine", label: "第2機械室へ行って", cost: 25, scene: "machine", facts: ["F02"] },
  find_code: { id: "find_code", label: "コードを探して", cost: 25, facts: ["F03"], lines: [y("保守用のパネルを外す。少し待って"), y("あった。手書きの番号……7319。これが非常電源のコード")] },
  enable_power: { id: "enable_power", label: "7319 を入力", cost: 8, scene: "powered", facts: ["F03"], trust: -1 },
  admin: { id: "admin", label: "管理者権限を使って", cost: 12, lines: [s("ADMIN AUTHENTICATION UNAVAILABLE"), y("管理サーバーに繋がらない。保守パネルに非常電源のコードがないか探せる")] },
  back: { id: "back", label: "操作メニューに戻る", cost: 0 },
  open_door: { id: "open_door", label: "第4区画の扉を開けて", cost: 8, scene: "escaping", lines: [y("やってみる"), s("LOCK RELEASED"), y("開いた。通路に出る！")] },
  tank: { id: "tank", label: "水槽07を確認する", cost: 12, scene: "tank", lines: [y("……本気？"), p("必要だ"), y("監視映像を開く。何も見えない。水槽の中、真っ暗", "IMG_05", "quiet")] },
  vitals: { id: "vitals", label: "生体反応は？", cost: 8, facts: ["F14"], lines: [y("ゼロ。そんなはずない", undefined, "quiet")] },
  brighten: { id: "brighten", label: "映像を明るくして", cost: 8, lines: [y("明るさを上げた。これは……反射？", "IMG_06", "quiet")] },
  audio: { id: "audio", label: "音声ログを確認", cost: 15, facts: ["F10", "F11"], lines: [s("TANK-07 / AUDIO ARCHIVE\n『こんにちは』『ユナ』『こんにちは』"), y("……これ。私の声", undefined, "quiet"), s("VOCAL MIMICRY CONFIRMED / LANGUAGE LEARNING IN PROGRESS")] },
  security: { id: "security", label: "監視ログを見る", cost: 15, scene: "security", facts: ["F12"], lines: [s("17 MIN BEFORE INCIDENT"), y("……私？", "IMG_07", "quiet"), p("覚えてない？"), y("行ってない", undefined, "quiet")] },
  next_security: { id: "next_security", label: "5分前の記録を見る", cost: 12, facts: ["F13"], lines: [s("5 MIN BEFORE INCIDENT"), y("同じ場所に、立ってる。ずっと動かない", "IMG_08", "quiet"), s("SUBJECT YUNA / NO RESPONSE\nVIDEO FEED INTERRUPTED", "quiet")] },
  question_identity: { id: "question_identity", label: "君、本当にユナ？", cost: 10, scene: "identity", lines: [y("何言ってるの", undefined, "quiet"), p("事故の5分前から君は応答してない"), s("TRANSMISSION DELAY / 5 SEC", "quiet"), y("……それ、誰から聞いたの？", undefined, "quiet")] },
  reassure: { id: "reassure", label: "信じて。時間がない", cost: 6, trust: 1 },
  central: { id: "central", label: "中央管理端末にアクセス", cost: 10, scene: "central", facts: ["F04"], lines: [s("CENTRAL CONTROL ONLINE\nISOLATION PROTOCOL ACTIVE"), y("隔離、圧力制御、通信履歴にアクセスできる")] },
  protocol: { id: "protocol", label: "隔離プロトコル", cost: 3, scene: "protocol", facts: ["F04"], lines: [s("ISOLATION PROTOCOL ACTIVE\nMAINTAIN / REINFORCE / RELEASE")] },
  pressure: { id: "pressure", label: "圧力制御を確認", cost: 8, scene: "pressure", facts: ["F05"], lines: [s("SECTION-07 / DRAINAGE PUMP: ACTIVE\nCONTAINMENT PRESSURE: RISING"), y("水槽07の隔離を解除すれば、自動封鎖も停止する"), y("保守手順に注意書きがある。『水槽07開放時は、先に第7区画排水ポンプを停止すること』")] },
  pressure_details: { id: "pressure_details", label: "なぜ圧力が上がる？", cost: 8, facts: ["F05"], lines: [y("排水と隔離が同時に動いて、圧力差が広がってる"), y("ポンプを停止してから水槽07を開けば、圧力も、自動封鎖も止まるはず")] },
  stop_pump: { id: "stop_pump", label: "第7区画の排水ポンプを停止", cost: 10, scene: "central", lines: [y("そんなことしたら水槽側の圧力が――"), p("止めて"), s("DRAINAGE OFFLINE\nSECTION-07 PRESSURE EQUALIZING"), y("止まった。隔離を解除できる")] },
  comms: { id: "comms", label: "通信回線を調べる", cost: 5, scene: "comms", lines: [s("AUX-07 / MAINTENANCE LINK\nINCIDENT BUFFER AVAILABLE")] },
  history: { id: "history", label: "通信履歴と施設の時計を照合", cost: 12, facts: ["F20"], lines: [s("FACILITY CLOCK: CONTINUOUS\nAUX-07 RECORD TIMESTAMP: REPEATING"), y("施設の時計は戻ってない。なのに、この回線だけ同じ3分間を繰り返してる……？")] },
  signal: { id: "signal", label: "信号の発信元は？", cost: 8, lines: [s("SOURCE: AUX-07 / INCIDENT BUFFER\nADDITIONAL SOURCE: UNRESOLVED"), y("発信元が、一つじゃない。水槽の回線が混じってる") ] },
  maintain: { id: "maintain", label: "隔離を維持", cost: 5, scene: "pressure_failure", lines: [s("CONTAINMENT MAINTAINED\nPRESSURE RISING", "glitch"), y("待って、隔壁が軋んでる。圧力が逃げない") ] },
  reinforce: { id: "reinforce", label: "隔離を強化", cost: 5, scene: "pressure_failure", lines: [s("CONTAINMENT REINFORCED\nPRESSURE CRITICAL", "glitch"), y("余計に圧力が上がった……！") ] },
  request_release: { id: "request_release", label: "隔離プロトコルを解除", cost: 3, scene: "release_confirm", facts: ["F04"] },
  release: { id: "release", label: "開ける", cost: 18 },
  refuse: { id: "refuse", label: "やめる", cost: 3, scene: "pressure_failure", lines: [y("……そうだね。開けるわけにはいかない"), s("CONTAINMENT PRESSURE RISING", "glitch")] },
  alternative: { id: "alternative", label: "別の方法を探す", cost: 10, scene: "pressure_failure", lines: [y("他の経路も、全部隔離されてる"), s("CONTAINMENT PRESSURE CRITICAL", "glitch")] },
  wait: { id: "wait", label: "応答を待つ", cost: 20 },
  unknown_identity: { id: "unknown_identity", label: "君は水槽07？", cost: 0 },
};

export const SCENE_CHOICES: Record<string, string[]> = {
  intro: ["hello", "name", "incident_intro"],
  contact: ["incident", "location", "escape", "more"],
  questions: ["power_location", "tank_question", "other_people", "go_machine"],
  surroundings: ["break_door", "reassure", "go_machine", "back"],
  machine: ["find_code", "enable_power", "admin", "back"],
  powered: ["open_door", "tank", "security", "central"],
  tank: ["vitals", "brighten", "audio", "back"],
  security: ["next_security", "question_identity", "reassure", "back"],
  identity: ["reassure", "question_identity", "central", "back"],
  central: ["protocol", "pressure", "comms", "back"],
  protocol: ["maintain", "reinforce", "request_release", "back"],
  pressure: ["stop_pump", "pressure_details", "protocol", "back"],
  comms: ["history", "signal", "question_identity", "back"],
  release_confirm: ["release", "refuse", "alternative", "pressure"],
  escaping: ["wait"],
  pressure_failure: ["wait"],
  unknown: ["unknown_identity"],
};

/** Normalize before lookup; knowledge changes suggestions, never validity. */
export const KEYWORDS: Record<string, string[]> = {
  hello: ["聞こえる"], name: ["誰", "名前は", "ユナ", "yuna"], incident: ["何が起きた", "何が起きてる"],
  location: ["今どこ", "現在地", "第4研究区画"], escape: ["逃げられない", "脱出できる"],
  power_location: ["非常電源はどこ", "電源はどこ"], tank_question: ["水槽07って何", "水槽07とは"],
  other_people: ["他に人は"], break_door: ["扉を壊せない", "扉を壊して"],
  go_machine: ["第2機械室", "第2機械室へ", "第2機械室へ行って", "第2機械室に行って", "機械室へ"],
  find_code: ["コードを探して", "コードを探す", "非常電源のコード", "コードは"],
  enable_power: ["7319", "7319を入力", "コード7319", "非常電源コード7319", "非常電源コードは7319", "非常電源コードは7319です", "非常電源コード:7319"],
  admin: ["管理者権限", "管理者権限を使って"],
  open_door: ["第4区画を開ける", "第4区画の扉を開けて", "扉を開けて"],
  tank: ["水槽07", "tank07", "tank-07", "水槽07を確認", "水槽07を確認して"],
  vitals: ["生体反応", "生体反応は"], brighten: ["映像を明るくして", "明るくして"], audio: ["音声ログ", "音声ログを確認"],
  security: ["監視ログ", "監視ログを見る", "17分前"], next_security: ["5分前", "5分前の記録", "次の映像"],
  question_identity: ["君本当にユナ", "本当にユナ", "あなたは本当にユナ", "君は本当にユナ", "事故の5分前から君は応答してない"],
  reassure: ["信じて時間がない", "信じて", "非常電源が必要になる", "落ち着いて", "説明している時間がない"],
  central: ["中央管理端末", "中央端末", "中央管理端末にアクセス"], protocol: ["隔離プロトコル", "isolation"],
  pressure: ["圧力制御", "圧力を確認", "排水ポンプ", "第7区画"], pressure_details: ["なぜ圧力が上がる", "隔離そのものが事故原因"],
  stop_pump: ["第7区画の排水ポンプを停止", "第7区画排水ポンプを停止", "第7区画の排水ポンプ停止", "第7区画排水ポンプ停止", "排水ポンプを停止", "排水ポンプ停止", "ポンプを止めて", "排水ポンプを止めて", "drainageoff"],
  comms: ["通信回線", "通信回線を調べる"], history: ["通信履歴", "履歴", "時間を巻き戻している", "ループ"], signal: ["信号の発信元", "発信元"],
  maintain: ["維持", "隔離を維持"], reinforce: ["強化", "隔離を強化"],
  request_release: ["隔離解除", "隔離を解除", "隔離プロトコルを解除", "水槽07の隔離を解除", "isolationrelease"],
  release: ["開ける", "開けて", "そう", "解除する", "解除を実行"], refuse: ["やめる", "やめて"], alternative: ["別の方法を探す"],
  back: ["戻る", "操作メニュー"], wait: ["待つ", "待って"], unknown_identity: ["君は水槽07", "あなたは水槽07"],
};
